from __future__ import absolute_import

import albert.acquisition_functions.sequence_tagging.simple.least_confidence
import albert.acquisition_functions.sequence_tagging.simple.mnlp
import albert.acquisition_functions.sequence_tagging.simple.multilingual_mnlp

# import albert.acquisition_functions.sequence_tagging.simple.maximum_normalized_log_probability_with_fixed_lang_budget
import albert.acquisition_functions.sequence_tagging.simple.token_entropy
import albert.acquisition_functions.sequence_tagging.simple.total_token_entropy
